# Generated by Django 4.2 on 2025-02-01 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile"),
        ("blog", "0003_alter_post_auther"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="auther",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profile",
            ),
        ),
    ]
